### ISSUE TITLE
maven编译错误

### ISSUE THREAD

**Issue by paddy235** [hs-web/hsweb-easy-orm#1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project hsweb-easy-orm-es: Compilation failure
[ERROR] /git/hsweb-easy-orm/hsweb-easy-orm-es/src/main/java/org/hsweb/ezorm/es/simple/SimpleESQuery.java:[18,1] org.hsweb.ezorm.es.simple.SimpleESQuery不是抽象的, 并且未覆盖org.hsweb.ezorm.core.Conditional中的抽象方法sql(java.lang.String,java.lang.Object...)

**Comment by zhou-hao** [comment]
之前修改没提交，现在应该可以了
