### ISSUE TITLE
TermType

### ISSUE THREAD

**Issue by ylzhang0510** [hs-web/hsweb-easy-orm#22]
postgresql中查询时大小写敏感的，需要使用ILIKE关键字，但是TermType未定义，有其他方式可以实现吗

**Comment by zhou-hao** [comment]
可以自定义，TermFragmentBuilder设置到schema中。如果是在hsweb中。推荐：实现AbstractTermFragmentBuilder然后注入到spring即可。

发自我的iPhone


------------------ Original ------------------

**Comment by ylzhang0510** [comment]
非常感谢，我试试
